sudo: true
dist: bionic
language: node_js
node_js: 'lts/*'

services:
  - docker

branches:
  only:
    - develop
    - master
    - /^((hotfix|feature|release)\/)$/

stages:
  - unit_test
  - e2e_test
  - build_and_push

jobs:
  include:
    - stage: unit_test
      script:
        # - npm audit --audit-level=high
        - bash ./scripts/setupUnitTest.sh
        - npm run coverage-codecov
      name: test:mocha
      env:
        - ROCKET_CHAT_URI=http://localhost:5000
      cache: npm
    - stage: e2e_test
      script: curl "https://raw.githubusercontent.com/hpi-schul-cloud/end-to-end-tests/master/scripts/ci/fetch.travis.sh" | bash
      name: "test:end-to-end"
      env:
        - DOCKER_COMPOSE_VERSION=1.27.4
      cache: npm
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - echo "skipping install"
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log
    - stage: build
      if: NOT fork
      script:
        - ./build.sh
      name: build_and_push
      language: generic
      env:
        - GIT_SHA=$( git rev-parse HEAD )
        - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
      install:
        - mkdir -p .build
        - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out .build/travis_rsa -d
        - cat /home/travis/.npm/_logs/*debug.log