sudo: true
dist: bionic
language: node_js
node_js: 'lts/*'

services:
  - docker

branches:
  only:
    - develop
    - master
    - /^((hotfix|feature|release)\/)$/

stages:
  - test
  - deploy

jobs:
  include:
    - script:
        - bash ./scripts/setupUnitTest.sh
        - npm run coverage-codecov
      name: test:mocha
    - script: curl "https://raw.githubusercontent.com/hpi-schul-cloud/end-to-end-tests/master/scripts/ci/fetch.travis.sh" | bash
      name: "test:end-to-end"
      env:
        - DOCKER_COMPOSE_VERSION=1.27.4
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - echo "skipping install"
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log
    - stage: deploy
      if: NOT fork
      script:
        - ./build.sh
      name: build_and_push
      language: generic
      env:
        - GIT_SHA=$( git rev-parse HEAD )
        - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log