dist: focal
language: node_js
node_js: 'lts/*'

services:
  - docker

branches:
  only:
    - develop
    - master
    - /^((hotfix|feature|release|dependabot)\/.*)$/

stages:
  - test
  - deploy

jobs:
  include:
    - script:
        - bash ./scripts/unitTest.sh
        - npm run coverage-codecov
      name: test:mocha
#   ------------
#    - script: bash ./scripts/e2eTest.sh
#      name: "test:end-to-end"
#      after_failure:
#        - cat /home/travis/.npm/_logs/*debug.log
#   ------------
    - script: curl "https://raw.githubusercontent.com/hpi-schul-cloud/end-to-end-tests/master/scripts/ci/fetch.travis.sh" | bash
      name: "test:end-to-end"
      env:
        - DOCKER_COMPOSE_VERSION=1.27.4
      cache: npm
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - echo "skipping install"
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log
#   ------------
    - stage: deploy
      if: NOT fork
      script:
        - ./scripts/build.sh
      name: build_and_push
      language: generic
      env:
        - GIT_SHA=$( git rev-parse HEAD )
        - DOCKERTAG=$( echo $TRAVIS_BRANCH | tr -s "[:punct:]" "-" )
      after_failure:
        - cat /home/travis/.npm/_logs/*debug.log
