security:
  - jwtBearer: []
info:
  title: Schul-Cloud Authentication Service API
  description:
    This is the API specification for the Schul-Cloud Authentication service.
    
  contact:
    name: support
    email: info@hpi-schul-cloud.de
  license:
    name: GPL-3.0
    url: 'https://github.com/hpi-schul-cloud/schulcloud-server/blob/master/LICENSE'
  version: 1.0.0
components:
  securitySchemes:
    jwtBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    authentication_body:
      description: Payload for an authentication request
      allOf:
        - properties:
            strategy:
                type: string
                enum: ['local', 'ldap', 'moodle', 'iserv', 'tsp']
            username:
              type: string
            password:
              type: string
            privateDevice:
              type: boolean
              description: when this is set, the user will remain logged in for longer when inactive.
            systemId:
              type: string
              pattern: '^[0-9a-f]{24}$'
            schoolId:
              type: string
              pattern: '^[0-9a-f]{24}$'
          required:
            - username
            - password
            - strategy
    authentication_response:
      description: TODO
      properties:
        accessToken:
          type: string
        account:
          type: object
          properties:
            __v:
              type: integer
            _id:
              type: string
              pattern: '^[0-9a-f]{24}$'
            activated:
              type: boolean
            createdAt:
              type: string
              format: date-time
            lasttriedFailedLogin:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
            userId:
              type: string
              pattern: '^[0-9a-f]{24}$'
            username:
              type: string
        authentication:
          type: object
          properties:
            strategy:
              type: string
              enum: ['local', 'ldap', 'moodle', 'iserv', 'tsp']

paths:
  /authentication:
    post:
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authentication_response'
        '401':
          description: not authenticated
        '500':
          description: general error
      description: Logs in the user based on authentication data.
      summary: ''
      tags:
        - authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authentication_body'
  '/authentication/{id}':
    delete:
      parameters:
        - in: path
          name: id
          description: ID of authentication to remove
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authentication'
        '401':
          description: not authenticated
        '404':
          description: not found
        '500':
          description: general error
      description: Removes the resource with id.
      summary: ''
      tags:
        - authentication
      security: []
openapi: 3.0.2
tags:
  - name: authentication
    description: A authentication service.


